#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$Owner,
    [string]$Repository,
    [string]$Branch
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$utf8 = New-Object System.Text.UTF8Encoding($false)
$utf8Bom = New-Object System.Text.UTF8Encoding($true)
$configPath = Join-Path $root 'repo.json'
$config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
$oldRaw = 'https://raw.githubusercontent.com/{0}/{1}/{2}' -f $config.owner, $config.repository, $config.branch
$oldRepo = 'https://github.com/{0}/{1}' -f $config.owner, $config.repository
$oldPages = 'https://{0}.github.io/{1}/' -f $config.owner.ToLowerInvariant(), $config.repository
$oldIdentity = '{0}/{1}' -f $config.owner, $config.repository
if ($Owner) { $config.owner = $Owner }
if ($Repository) { $config.repository = $Repository }
if ($Branch) { $config.branch = $Branch }
if ($config.owner -notmatch '^[A-Za-z0-9][A-Za-z0-9-]*$' -or
    $config.repository -notmatch '^[A-Za-z0-9][A-Za-z0-9_.-]*$' -or
    $config.branch -notmatch '^[A-Za-z0-9][A-Za-z0-9_.-]*$') {
    throw 'Use a valid GitHub owner/repository and a simple branch name (for example main).'
}
$raw = 'https://raw.githubusercontent.com/{0}/{1}/{2}' -f $config.owner, $config.repository, $config.branch
$repo = 'https://github.com/{0}/{1}' -f $config.owner, $config.repository
$pages = 'https://{0}.github.io/{1}/' -f $config.owner.ToLowerInvariant(), $config.repository
$items = @(
    @{ id = 'fixpack'; file = 'ChatGPT_LeHaut_Fixpack.user.js'; original = 'ChatGPT_LeHaut_Fixpack_v1.0.0.user.js' },
    @{ id = 'search'; file = 'ChatGPT_Message_Search_LeHaut.user.js'; original = 'ChatGPT_Message_Search_LeHaut_v1.2.0.user.js' },
    @{ id = 'exporter'; file = 'ChatGPT_RP_Exporter_GUI.user.js'; original = 'ChatGPT_RP_Exporter_GUI_v0.2.0.user.js' }
)
$manifest = @()
foreach ($item in $items) {
    $path = Join-Path $root ('userscripts/' + $item.file)
    $sourcePath = $path
    if (-not (Test-Path -LiteralPath $path)) { $sourcePath = Join-Path $root ('archive/' + $item.original) }
    $source = [IO.File]::ReadAllText($sourcePath)
    $end = $source.IndexOf('// ==/UserScript==')
    if ($end -lt 0) { throw "Missing userscript header: $sourcePath" }
    $header = $source.Substring(0, $end)
    $body = $source.Substring($end)
    $nl = "`n"
    if ($header.Contains("`r`n")) { $nl = "`r`n" }
    $header = [regex]::Replace($header, '(?m)^//\s+@(updateURL|downloadURL)\s+[^\r\n]*\r?\n', '')
    $url = "$raw/userscripts/$($item.file)"
    $header += "// @updateURL    $url$nl// @downloadURL  $url$nl"
    [IO.File]::WriteAllText($path, $header + $body, $utf8)
    $version = [regex]::Match($header, '(?m)^//\s+@version\s+(\S+)').Groups[1].Value
    if (-not $version) { throw "Missing version: $path" }
    $manifest += [ordered]@{ id = $item.id; file = $item.file; version = $version; url = $url }
}
$siteConfig = [ordered]@{
    repositoryUrl = $repo
    pagesUrl = $pages
    command = "irm $raw/install.ps1 | iex"
    scripts = $manifest
}
[IO.File]::WriteAllText((Join-Path $root 'docs/config.js'), "// Generated by scripts/configure-repo.ps1. Do not edit by hand.`nwindow.LEHAUT_CONFIG = " + ($siteConfig | ConvertTo-Json -Depth 5) + ";`n", $utf8)
foreach ($name in @('README.md', 'docs/index.html', 'install.ps1')) {
    $path = Join-Path $root $name
    if (Test-Path -LiteralPath $path) {
        $text = [IO.File]::ReadAllText($path).Replace($oldRaw, $raw).Replace($oldRepo, $repo).Replace($oldPages, $pages).Replace($oldIdentity, ('{0}/{1}' -f $config.owner, $config.repository))
        $encoding = $utf8
        if ($name -eq 'install.ps1') { $encoding = $utf8Bom }
        [IO.File]::WriteAllText($path, $text, $encoding)
    }
}
[IO.File]::WriteAllText($configPath, ($config | ConvertTo-Json) + "`n", $utf8)
Write-Host "Configured: $repo"
Write-Host "Installer:  $pages"
Write-Host "irm $raw/install.ps1 | iex"
